resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
- name: bosh-lite-pipeline
  type: git
  source:
    uri: https://github.com/DanielJonesEB/bosh-lite-pipeline.git
- name: iaas
  type: terraform
  source:
    storage:
      bucket: bosh-lite-pipeline
      bucket_path: terraform-ci/
      access_key_id: ((concourse_ci_s3_access_key))
      secret_access_key: ((concourse_ci_s3_secret_key))

jobs:
- name: pave
  plan:
  - get: bosh-lite-pipeline
    trigger: true
  - put: iaas
